### ISSUE TITLE
Disable Triggers On Related Entities

### ISSUE THREAD

**Issue by mglodack** [NickStrupat/EntityFramework.Triggers#10]
I have a question about disabling triggers on related models.

Lets say I have `ModelA` and that has many `ModelB`s. I have a trigger on both for Updating.

However, my trigger in `ModelA` is updating its related `ModelB`s which causes the updating trigger to be called for `ModelB`.

Is there any way to disable triggers on `ModelB` if it's being updated from `ModelA`s trigger?

**Comment by NickStrupat** [comment]
So you have a `ModelA` update trigger which changes some `ModelB`s, which have update triggers that change some `ModelA`s?

What is the specific need for that?

Which version of EntityFramework.Triggers are you using?

**Comment by mglodack** [comment]
Using EF Core triggers.

It's a linear update. 

I'm only updating a `ModelB` from `ModelA` which causing `ModelB`s triggers to also be called.

I'm using these triggers to update properties on both the parent entity `ModelA` as well as it's child entity `ModelB`.

**Comment by NickStrupat** [comment]
Ah, I see the value in that ability. It would be useful to have the ability to, within a given trigger, prevent the changes made within that trigger from registering as trigger-able changes.

I'll tinker with this in a couple of days. Merry Christmas!

**Comment by NickStrupat** [comment]
So I'm thinking that adding a method/property to `IBeforeEntry<T>` called `CancelNestedTriggers` or something more terse would be the right API for this feature, given the existing API.

**Comment by mglodack** [comment]
Sweet! Got an example of what the implementation and the call-site might look like?

**Comment by NickStrupat** [comment]
I haven't settled on a property name yet, but it would look like...

```csharp
Triggers<ModelA>.Updating += e => {
    e.IncurTriggers = false;
    e.ModelB.Foo++;
}
Triggers<ModelB>.Updating += e => e.Updated = DateTime.UtcNow; // this wouldn't run as a result of the trigger above running, as it normally would
```

I'm still having trouble imagining a scenario where you would not want the related triggers to fire. Could you post an/your example?
