### ISSUE TITLE
Not working with Tracker Enabled DBContext 

### ISSUE THREAD

**Issue by Anton-Interon** [NickStrupat/EntityFramework.Triggers#14]
Hi Great Package 

I was hoping you could shed some light as to why your package does't work when trying to use it with 
Tracker Enabled DBContext 
https://github.com/bilal-fazlani/tracker-enabled-dbcontext

TEDB uses attributes where yours inherits from Trackable

where Trackable does initialize but the events never fire.

```
 static Trackable()
        {
            Triggers<Trackable>.Inserting += entry => entry.Entity.Inserted = entry.Entity.Updated = DateTime.Now;
            Triggers<Trackable>.Updating += entry => entry.Entity.Updated = DateTime.Now;
        }

```
Any help will be appreciated.

**Comment by NickStrupat** [comment]
Hi, thank you,

My guess is that you're inheriting from `TrackerContext` which doesn't call the trigger-firing code of my `DbContextWithTriggers`.

If that is indeed the case the solution is simple: you need to override the `SaveChanges` methods in your context class. You can see how to do this here https://github.com/NickStrupat/EntityFramework.Triggers/blob/master/README.md#manual-overriding-to-enable-triggers

**Comment by Anton-Interon** [comment]
Strange that is what I did but for some reason, SaveChangesAsync does not override. when calling SaveChanges() all works well.

**Comment by NickStrupat** [comment]
Ah, I checked what `TrackerContext` is doing. It's overriding the `DbContext.SaveChanges...` overloads, as well as defining several new overloads. Usually the two overloads just forward default arguments to the actual implementation.

So, you'll need to override all declarations of `SaveChanges` to call the corresponding `SaveChangesWithTriggers...`. Be careful overriding the new overloads declared by `TrackerContext`.

**Comment by aboyaniv** [comment]
hello.

I had the same problem , I have create a new "TrackerContext"  ( copy form the original ) and change the SaveChanges to SaveChangesWithTriggers 
see 
    ` 


            public virtual int SaveChanges(object userName)
        {
            if (!TrackingEnabled) return this.SaveChangesWithTriggers(base.SaveChanges);

            dynamic metaData = new ExpandoObject();
            _metadataConfiguration?.Invoke(metaData);

            _coreTracker.AuditChanges(userName, metaData);

            IEnumerable<DbEntityEntry> addedEntries = _coreTracker.GetAdditions();
            // Call the original SaveChanges(), which will save both the changes made and the audit records...Note that added entry auditing is still remaining.
            int result = this.SaveChangesWithTriggers(base.SaveChanges);
            //By now., we have got the primary keys of added entries of added entiries because of the call to savechanges.

            _coreTracker.AuditAdditions(userName, addedEntries, metaData);

            //save changes to audit of added entries
            this.SaveChangesWithTriggers(base.SaveChanges);
            return result;
        }`

**Comment by NickStrupat** [comment]
Hi there,

Are you overriding all of the overloads correctly?

**Comment by aboyaniv** [comment]
it's working 👍
