### ISSUE TITLE
The extension SaveChangesWithTriggersAsync is not available in nuget package

### ISSUE THREAD

**Issue by ftoyon** [NickStrupat/EntityFramework.Triggers#2]
The nuget package version 5.0.3 does not contains the extension SaveChangesWithTriggersAsync.

**Comment by NickStrupat** [comment]
It is not available in the .NET 4 build, but it is available with the .NET 4.5.1 build. Is your project set to target .NET 4 or 4.5.1?

**Comment by ftoyon** [comment]
It is a 4.5 project.

**Comment by NickStrupat** [comment]
So the issue is that just the .NET 4.0 and .NET 4.5.1 builds are in the NuGet package. If you can easily switch to targeting .NET 4.5.1, you can have the ...Async functions right away. I will put the .NET 4.5 build in a 5.0.4 package in a couple of hours, if you'd rather wait for that.

**Comment by NickStrupat** [comment]
I have published a package (5.0.4) with a build targeting .NET 4.5

**Comment by ftoyon** [comment]
It's working fine.

Thanx for your work.
