### ISSUE TITLE
Insert null after update 

### ISSUE THREAD

**Issue by Anton-Interon** [NickStrupat/EntityFramework.Triggers#21]
Hi Nick

I hope you are well.

I have a problem here where when I insert a record the Insert and Update Columns gets set and all is fine 
When I do an update the Update Column is set but the Insert column get sets to null

`public abstract class Trackable
    {
        public virtual DateTime? Inserted { get; private set; }
        public virtual DateTime? Updated { get; private set; }

        static Trackable()
        {
            Triggers<Trackable>.Inserting += entry => entry.Entity.Inserted = entry.Entity.Updated = DateTime.Now;
            Triggers<Trackable>.Updating += entry => entry.Entity.Updated = DateTime.Now;
        }
    }`

```
#region If you're targeting EF 6
        public override int SaveChanges()
        {
            return this.SaveChangesWithTriggers(base.SaveChanges);
        }
        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken)
        {
             return await this.SaveChangesWithTriggersAsync(base.SaveChangesAsync, cancellationToken);
        }

        #endregion
```

 ```
public class PerformanceReviewMaster: Trackable
    {
        [Required,Key]
        public Guid PerformanceReviewMasterId { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }
      
    }
```

**Comment by Anton-Interon** [comment]
I forget to mention I'm on ver 6.08 when trying to upgrade to 6.1 I get 

: Could not install package 'EntityFramework.TypedOriginalValues 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content

**Comment by Anton-Interon** [comment]
Man I hope you can help me I'm 99.9% finished with a 6 month project and I realise this at the last minute

**Comment by NickStrupat** [comment]
Hi Anton,

That is strange indeed. I can help you tonight once I'm home from work. I hope that's ok for you time-wise.

Nick

**Comment by Anton-Interon** [comment]
Hi Nick
Thanks for getting back to me.
No problem. I'll wait up for you for it is 21:30 here in South Africa

**Comment by NickStrupat** [comment]
Hi Anton,

I stopped supporting .net 4.5 at the 6.1 release. Is there a chance you can quickly re-target your project to `.NET Framework 4.6.1`?

**Comment by NickStrupat** [comment]
I pushed a EF.TRiggers 6.1.1 with some small fixes to mistakes I made in the package and one of its dependencies. no code changes though. Please let me know if upgrading to 6.1.1 fixes your null insert issue or not.

**Comment by Anton-Interon** [comment]
Done targeting 4.6.1 and Upgraded to 6.1.1 but still having  the same problem

**Comment by NickStrupat** [comment]
So I just made a new .NET 4.6.1 console application, installed `EntityFramework.Triggers` `6.1.1` and ran this code in `DEBUG` build with no errors, running as expected. Can you try this on your machine?

```csharp
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Diagnostics;
using EntityFramework.Triggers;

namespace EfTriggersIssue21
{
	class Program
	{
		static void Main(string[] args)
		{
			using (var context = new Context())
			{
				var performanceReviewMaster = new PerformanceReviewMaster()
				{
					PerformanceReviewMasterId = Guid.NewGuid(),
					Description = "test",
					StartDate = new DateTime(1950, 1, 1),
					EndDate = new DateTime(1950, 1, 1)
				};
				context.PerformanceReviewMasters.Add(performanceReviewMaster);
				context.SaveChanges();
				Debug.Assert(performanceReviewMaster.Inserted != null);
				Debug.Assert(performanceReviewMaster.Updated != null);
				performanceReviewMaster.Description = "change";
				context.SaveChanges();
				Debug.Assert(performanceReviewMaster.Inserted != null);
				Debug.Assert(performanceReviewMaster.Updated != null);
			}
		}
	}

	class Context : DbContextWithTriggers
	{
		public virtual DbSet<PerformanceReviewMaster> PerformanceReviewMasters { get; set; }
	}

	public abstract class Trackable
	{
		public virtual DateTime? Inserted { get; private set; }
		public virtual DateTime? Updated { get; private set; }

		static Trackable()
		{
			Triggers<Trackable>.Inserting += entry => entry.Entity.Inserted = entry.Entity.Updated = DateTime.Now;
			Triggers<Trackable>.Updating += entry => entry.Entity.Updated = DateTime.Now;
		}
	}

	public class PerformanceReviewMaster : Trackable
	{
		[Required, Key]
		public Guid PerformanceReviewMasterId { get; set; }

		[Required]
		public string Description { get; set; }

		[Required]
		[DataType(DataType.Date)]
		public DateTime StartDate { get; set; }

		[Required]
		[DataType(DataType.Date)]
		public DateTime EndDate { get; set; }

	}
}

```

**Comment by Anton-Interon** [comment]
Hi Nick

Thanks for your help. Your code ran as expected. The problem actually comes in with MVC with code first where the Insert and Update get mapped through migration. Sorry man this is so obvious. Feel like a dumbass for not seeing it earlier.

Thanks Again for your help.
