### ISSUE TITLE
Updating event, the Original property can't fetch.

### ISSUE THREAD

**Issue by jhh0111** [NickStrupat/EntityFramework.Triggers#24]
Updating event, the Original property can't fetch，because it want to create a dynamic type inherit the EF's dynamic type, but EF's dynamic type is sealed. 
![image](https://user-images.githubusercontent.com/12031005/35429637-e044cf56-02af-11e8-8e30-00f4adbaa3b0.png)

**Comment by Hoshinokoe** [comment]
I've got the same exception when trying to access Original property:
```
{System.TypeLoadException: Declaration referenced in a method implementation cannot be a final method.  Type: 'Order__OriginalValuesWrapper'.  Assembly: 'Order__OriginalValuesWrapperAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at EntityFrameworkCore.TypedOriginalValues.OriginalValuesWrapper`1.GetFactory()
   at EntityFrameworkCore.TypedOriginalValues.OriginalValuesWrapper`1..cctor()}
```

Model class:
```
public class Order
{
    public Guid Id { get; set; }
    public Guid ProductId { get; set; }
    public Guid CustomerId { get; set; }

    public Product Product { get; set; }
    public Customer Customer { get; set; }
    public String Comment { get; set; }
    public OrderStatus Status { get; set; }

    public DateTime CreatedDate { get; set; }
    public DateTime UpdatedDate { get; set; }
    public User EditedBy { get; set; }

    public List<PeriodPrice> Intervals { get; set; }

    static Order()
    {
        Triggers<Order>.Inserting += entry => entry.Entity.CreatedDate = entry.Entity.UpdatedDate = DateTime.Now;
        Triggers<Order>.Updating += (entry) =>
        {
            var context = entry.Context;

            var original = context.GetOriginal(entry.Entity);    // this causes an exception
            var before = entry.Original;                                // this also

            entry.Entity.UpdatedDate = DateTime.Now;
        };
    }
}
```

**Comment by NickStrupat** [comment]
My apologies for the slow reply!

@Hoshinokoe, your properties need to be `virtual` to support the `Original` features

@jhh0111, you might have the same issue, although your description of your exception...

> because it want to create a dynamic type inherit the EF's dynamic type, but EF's dynamic type is sealed.

...suggests it may be something else.

**Comment by Hoshinokoe** [comment]
@NickStrupat , What is reason to make them virtual ?
I tested your solution and "Int", "String", "Boolean" properties don't require to be virtual.

**Comment by NickStrupat** [comment]
@Hoshinokoe they need to be virtual so the "original values" wrapper class can override the getters to retrieve their values from the `OriginalValues` bag. I'm not sure how the `int`, `string`, or `boolean` properties are working without it. Could you post your test?

**Comment by Hoshinokoe** [comment]
@NickStrupat Please see example in previous comment. All fields with virtual keyword except Comment and Status (which enum int).

**Comment by NickStrupat** [comment]
@Hoshinokoe I think you forgot to paste the code :)

**Comment by NickStrupat** [comment]
@Hoshinokoe they all need to be virtual. Did you solve your issue?

**Comment by Hoshinokoe** [comment]
@NickStrupat , Yes, it works perfect with virtual keyword. Thank you.
