### ISSUE TITLE
Double log entry on InsertFailed

### ISSUE THREAD

**Issue by koertner** [NickStrupat/EntityFramework.Triggers#25]
I am trying to create a trigger on insertFailed but when I try to save the Log for the failed action it actually refires the failed event so I am getting two log entries.  
I am logging to a separate database so I created a "saveLog" in the other project that I can use to perform the Save.

My Trigger:  
```csharp
Triggers<Unit>.InsertFailed += t =>
            {
                AuditLog log = new AuditLog();
                log.Action = "Insert";
                log.ModifyingCode = "Unit";
                log.WhatHappened = "Insert of new user failed." + t.Exception.InnerException.Message.ToString();
                
                AuditLogService.SaveAuditLog(log);
            };
```

In the SaveAuditLog
```csharp
public static void SaveAuditLog(AuditLog log)
        {
           LoggingDBContext context = new LoggingDBContext(builder.Options);

            context.Add(log);
            context.SaveChanges();
        }
```

Am I missing something to keep it from calling into the InserFailed trigger twice?  The SaveAuditLog does not produce an exception.

**Comment by NickStrupat** [comment]
Could you post a full example reproducing the double triggers behaviour?

**Comment by koertner** [comment]
What do you specifically need?  All I did was create a model (BTW this is .Net Core 2.0) and try to place triggers on it.  The insertFailed is called because when I am adding an entry in the model I left out a required field.  Do you need the entire solution?

Please let me know what you need to research this issue.

**Comment by koertner** [comment]
Looks like I might have figured out what was going wrong.  When you set the InsertFailed trigger and then spawn another log entry (as I am doing) I need to "Swallow" the original trigger.  I updated my InsertFailed below and now am getting only one log entry:
Triggers<Unit>.InsertFailed += t =>
            {
                LogTrigger log = new LogTrigger();
                log.Action = "Insert";
                log.ModifyingCode = "Unit";
                if (t.Exception.InnerException == null)
                {
                    log.WhatHappened = "Insert of new user failed." + t.Exception.Message.ToString();
                }
                else
                {
                    log.WhatHappened = "Insert of new user failed." + t.Exception.InnerException.Message.ToString();
                }
                t.Swallow = true;  //added this flag
                LogService.SaveAuditLog(log);
            };
