### ISSUE TITLE
Could you please provide a sample for EF Core 2? 

### ISSUE THREAD

**Issue by viveknuna** [NickStrupat/EntityFramework.Triggers#28]
Could you please provide a sample for adding a trigger, Condition is given it that I can't change your DbContext inheritance chain. If not possible then at least provide steps to create/alter/delete trigger, add migration and update database.

Further technical details:

Database engine: SQL Server

Visual Studio or SSMS version: Visual Studio 2017 15.5, SSMS 17.4

**Comment by NickStrupat** [comment]
https://github.com/NickStrupat/EntityFramework.Triggers#manual-overriding-to-enable-triggers

:)
