### ISSUE TITLE
How to get the package to work with dnx /ef7

### ISSUE THREAD

**Issue by darkurse** [NickStrupat/EntityFramework.Triggers#3]
Hi Nick,

do you plan to make your package work with ASP.NET 5 platform & ef7 soon ( even though it is in beta still ) ?

**Comment by NickStrupat** [comment]
I plan to do that in the next month or so. Do you have an immediate need for it?

**Comment by darkurse** [comment]
Well, that would be great of course. But I don't want to impose if you've already planned for this on your roadmap.

**Comment by NickStrupat** [comment]
Hi julienjuice, just wanted to give you an update. I've created a branch for EF7 support called... _drumroll_ 'ef7'. The unit tests are passing, but I still need to go over it in more detail this week. Anyway, if you need to get started, feel free to clone/branch 'ef7' and watch for updates from me.

**Comment by darkurse** [comment]
Cool, thanks
