### ISSUE TITLE
Set order of Triggers?

### ISSUE THREAD

**Issue by RKennedy9064** [NickStrupat/EntityFramework.Triggers#35]
Is it currently possible to set the calling order of triggers? I have a basic example that looks similar to this, minus the actual logic implemented.

    public abstact class Updatable
    {
        static Updatable()
        {
            Triggers<Updatable>.Updating += entry => {...};
        }
    }

    public class ModelA : Updatable
    {
        static ModelA()
        {
            Triggers<ModelA>.Updating += entry => {...};
        }
    }

The goal in my use case is to call the Updating trigger in ModelA before the generic Updating trigger in Updatable is called. Is it currently possible to do that, or am I approaching triggers in the wrong way? Any help would be greatly appreciated.

**Comment by RKennedy9064** [comment]
A quick edit to my original issue. I thought it might be possible to use the Updated trigger in the base class and use the original values after my model has been updated. I took a look at the code in the example and noticed something off. The example shows using Original on the entity like so.

    Triggers<ModelA>.Updated += e => Console.WriteLine("Updated " + e.Original.Value);

but it says that IUpdatedEntry does not contain a definition for Original. Is Original supposed to be accessible in the Updated trigger, or just Updating?

**Comment by NickStrupat** [comment]
It's only available on `Updating` and `Deleting` I believe. I didn't implement any new behaviour for that feature, it just wraps the EF method of retrieving the "original" values of the entity properties.

To answer your original question, triggers are fired from the base class, out. Just like constructors :)
