### ISSUE TITLE
trigger fires twice EFCore 2.2.0-preview3-35497

### ISSUE THREAD

**Issue by DerName** [NickStrupat/EntityFramework.Triggers#36]
The trigger is triggered 2 even though it has been saved only once:

`public partial class TblDatei
    {
        static TblDatei() =>
            Triggers<TblDatei>.Updated += e => { Console.WriteLine("Updated " + e.Entity.Guid); };
    }`

Saving:

`
 var dat = db.TblDatei.Where(s => s.Guid == "997F352E860C4D54B5CBBD2D7344FD06").FirstOrDefault();
            
                dat.Erstelldatum = "123456Y8";

                db.SaveChanges();
`

**Comment by NickStrupat** [comment]
#44 

did you ever resolve this?
