### ISSUE TITLE
No overload for method 'SaveChangesWithTriggers' takes 2 arguments

### ISSUE THREAD

**Issue by chetankhargone** [NickStrupat/EntityFramework.Triggers#38]
While trying to integrate this Trigger pack with a Stable ASP.Net Core 2.1 with EF Core 2.1. 

I am getting the error mentioned in the title.

Please find the complete app source at the below link. 
https://github.com/chetankhargone/Triggers-in-EF-COre.git

You could refer the SampleAppContext.cs for locating the error.

Can you please check & suggest on the same ?

Thanking You.

**Comment by SailorTurkey** [comment]
You are trying to use a .net 4.6.1 dll in a .net standart project. You can't reference non-standart dlls from standart libraries. You should change 'sample.dal' project to a .net 4.6.1 project or a .net core project.

**Comment by SailorTurkey** [comment]
You are referencing .net framework nuget package.
Try
https://www.nuget.org/packages/EntityFrameworkCore.Triggers/1.1.1

**Comment by chetankhargone** [comment]
@SailorTurkey Yes. You're right. Many Thanks!
