### ISSUE TITLE
Properties not getting updated

### ISSUE THREAD

**Issue by chetankhargone** [NickStrupat/EntityFramework.Triggers#39]
When I am inserting new entity, the Trackable propeteries Inserted & Updated is not getting the right value.

Please refer the app src at the below repository.
https://github.com/chetankhargone/Triggers-in-EF-COre.git

Can you please check & suggest ?

Thanking You.
![Db](https://user-images.githubusercontent.com/11959464/54420703-b9a34c80-4730-11e9-8c0e-60c52f31eb40.PNG)

**Comment by NickStrupat** [comment]
Hi @chetankhargone 

It looks like you are defining your own `DbContextWithTriggers` class, and also you aren't inheriting from it.

What you want to do is inherit your `SampleAppContext` from the `DbContextWithTriggers` class included in this library (so, delete your `DbContextWithTriggers` class). Like this...

```
class SampleAppContext : EntityFramework.Triggers.DbContextWithTriggers {

}
