### ISSUE TITLE
Properties are not being persisted inside Updating event

### ISSUE THREAD

**Issue by joshua-mng** [NickStrupat/EntityFramework.Triggers#40]
I'm having this strange bug.

Let's say I have this entity:

`
public class Subscription
{
  public long Id {get;set;}
  public decimal Amount {get;set;}
  public bool IsPaid {get;set;}
  public DateTime? PaidOnUtc {get;set;}
}

when I update, like this,
Triggers<Subscription>.Updating += context => {
  context.Entity.Amount = 30.0M;
};

using (var myTriggerContext = new MyTriggerContext()) {
  var existingSub = myTriggerContext.Subscriptions.FirstOrDefault(x => x.Id == 30);
  existingSub.PaidOnUtc = DateTime.UtcNow;
  await myTriggerContext.SaveChangesAsync();
}
`

Amount prop is never getting persisted. It persists only when following:
1) When I set Amount property explicity like: existingSub.Amount = 10M;
2) or when I call context.ChangeTracker.DetectChanges() method inside Updating event handler.

It seems to me that when we change entities inside Updating event handler, change tracker's DetectChanges method is not being called automatically in the base context's SaveChanges method.

Could you clarify the issue?

Thanks

**Comment by NickStrupat** [comment]
is your `MyTriggerContext` class inheriting from `DbContextWithTriggers`?
