### ISSUE TITLE
How to user this EntityFramework.Triggers with Repository pattern

### ISSUE THREAD

**Issue by umar-ulabs** [NickStrupat/EntityFramework.Triggers#43]
I am having hard time integration this library in my app, it has UnitOfWork and Repository pattern. I also want to pass logged in user info who performed the action from asp.net core to data layer. It seems this library can easily solve a complex issue in my app where I am logging in each controller.  Thank you

**Comment by NickStrupat** [comment]
I'm guessing you're looking for something like this...

```csharp
Triggers<Entity>.GlobalInserting.Add<IHttpContextAccessor>(e => {
    var user = e.Service.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
});
```

**Comment by UmarLone** [comment]
Should the above code in each entity class or in SaveChanges that exposed by Data Layer?. Thanks

**Comment by NickStrupat** [comment]
The code above should go wherever you want to initialize the triggers (generally you always want to do this once at start-up along with your other scaffolding).

It all depends when and where you want that trigger to be fired upon `SaveChanges()`
