### ISSUE TITLE
Support for EF 6.3.0 and Framework 4.6.1

### ISSUE THREAD

**Issue by landryn** [NickStrupat/EntityFramework.Triggers#48]
Hello, 

The package currently does not support EF 6.3 on Framework 4.6.1. Do you plan to support EF 6.3 on .Net 4.6?
![p](https://user-images.githubusercontent.com/214203/66492711-2018ff00-eab5-11e9-8858-1f27a79aedc6.PNG)

**Comment by NickStrupat** [comment]
Hi @landryn ,

You're right... I must have messed up the package spec. It should match the dependency table of EF 6.3:

![image](https://user-images.githubusercontent.com/782521/66497362-5f7e2600-ea8a-11e9-8fc4-2fbbc7cf5c04.png)

**Comment by landryn** [comment]
Hi, @NickStrupat, 

Thank you for your time. Unfortunately, this issue is blocking me EF updates. So I wanted to ask when you plan you plan to release a new version?

**Comment by NickStrupat** [comment]
@landryn I've published the updated package. It should be available whenever NuGet finishes indexing. Please let me know if it doesn't work for you :)

**Comment by NickStrupat** [comment]
closing assuming things are fine now

**Comment by landryn** [comment]
@NickStrupat now everything looks fine.  I'm most grateful to you for help, thanks.
