### ISSUE TITLE
Support for EF Core

### ISSUE THREAD

**Issue by mglodack** [NickStrupat/EntityFramework.Triggers#5]
Any idea if you are going to add support for Entity Framework Core?

**Comment by NickStrupat** [comment]
I will be supporting EF Core. Actually, before they renamed it to EF Core, when it was EF7, I did some work converting this project to work on EF7 on this branch: https://github.com/NickStrupat/EntityFramework.Triggers/tree/ef7

I never made a NuGet package for it. Also it's decently behind the master branch now.

:D

**Comment by mglodack** [comment]
That's so awesome 👍 Doesn't look like it was much work.

Yeah unfortunately they changed the name after they had already started calling it EF7 😞 

Are you looking to support EF6 and EF Core?

**Comment by NickStrupat** [comment]
Yes, I'm planning to support EF6 and EF Core for all of my EF projects :)

**Comment by NickStrupat** [comment]
Just wanted to give you an update...

I'm a couple of days away from having a new package called `EntityFrameworkCore.Triggers` which is for .NET 4.5 and .NET Core (EntityFrameworkCore runs on both of those platforms). It took a few days to get the dependent project, `EntityFramework.TypedOriginalValues` updated and learning how to do .NET Core, project.json, and NET Standard Platform stuff.

EntityFramework.Triggers will be the same old package for .NET 4.0 and .NET 4.5.

All the code will stay in this repository.
