### ISSUE TITLE
Example Syntax Not Working

### ISSUE THREAD

**Issue by baum-sparton** [NickStrupat/EntityFramework.Triggers#50]
Using Asp Net Core 2.2 with NickStrupat.EntityFrameworkCore.Triggers.AspNetCore 1.0.2

I'm trying to follow the examples on the github main page, but they are not working for me.

I have a DbContext derived from DbContextWithTriggers.
services.AddTriggers(); is called in Startup.ConfigureServices.

If I have the following in the Configure method nothing happens:
```
            app.UseTriggers(builder =>
            {
                builder.Triggers().Inserted.Add(  entry => logger.LogWarning("Please Log")  );
            });
```

This almost exactly matches the documentation but does not work.

The follow does however work:
```
            app.UseTriggers(builder =>
            {
                Triggers<EventNote>.Inserted += e => logger.LogWarning("I work");
                Triggers.Inserted += e => logger.LogWarning("me too");
            });
```

What am I missing?  What I am really looking for is to use the dependency injection syntax to pass the modified entry to a service.  Something like this for a single entity:
```
            app.UseTriggers(builder =>
            {
                builder.Triggers<EventNote, EntityContext>().Inserted.Add<TransactionLog>(entry =>
                {
                    entry.Service.LogEventNote(entry.Entity as EventNote );
                });
            });
```
Or preferably this for all entities:
```
            app.UseTriggers(builder =>
            {
                builder.Triggers().Inserted.Add<TransactionLog>(entry =>
                {
                    entry.Service.LogEntity(entry.Entity);
                });
            });
```

Also, are async triggers supported?  Something like:
```
            app.UseTriggers(builder =>
            {
                builder.Triggers().Inserted.Add<TransactionLog>(async entry =>
                {
                    await entry.Service.LogEntity(entry.Entity);
                });
            });
```

**Comment by NickStrupat** [comment]
By "not working", do you mean that the web app runs without errors, but the trigger handlers don't execute?

**Comment by baum-sparton** [comment]
Yes.  Application runs fine, triggers are just not executed.  It doesn't appear that any exceptions are occurring or errors are getting logged.

**Comment by NickStrupat** [comment]
Ok. If you clone this repo and then run `test/EntityFrameworkCore.Triggers.AspNetCore.Test`, do the trigger handlers run?

In case you haven't used `Debug.WriteLine` in ASP.NET, the messages go to the `Output` window.

**Comment by baum-sparton** [comment]
That project doesn't build.  Only that one, the other 12 build fine.

Error messages include:
NETSDK1045	The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1.
and
CS8107	Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.	EntityFramework.Triggers(netstandard2.1)

**Comment by NickStrupat** [comment]
Ah yes. The latest version of this project requires .NET Core 3.0 (.NET Standard 2.1).

**Comment by baum-sparton** [comment]
I'm locked at Core 2.2 at the moment and don't have a Core 3.0 build environment setup.

**Comment by NickStrupat** [comment]
Hm... this actually doesn't make sense. I think one of these project dependencies is wrong. My `EntityFrameworkCore.Triggers` package should have a .NET Standard 2.0 dependency along with .NET Standard 2.1 and .NET Framework 4.6.1.

**Comment by NickStrupat** [comment]
Could you try again with the latest packages? I believe I've fixed the issue.

**Comment by baum-sparton** [comment]
This issue appears to be fixed.  Using builder.Triggers to configure the triggers is working.  Thanks

**Comment by NickStrupat** [comment]
Awesome! Glad to hear it. You're welcome :)
