### ISSUE TITLE
Avoid adding multiple times the same handler callback to Triggers<TEntity, TDbContext>

### ISSUE THREAD

**Issue by falkartis** [NickStrupat/EntityFramework.Triggers#53]
If the execution flow passes multiple times through a line like this:
`Triggers<TBase, TContext>.GlobalInserted.Add(someCallback);`
The callback gets added each time, and the callback gets called also that many times. Is there a way to avoid this?

**Comment by NickStrupat** [comment]
Ideally you can refactor your code to only add each handler once. Otherwise, you could use a `HashSet<THandler>` to maintain the state of whether or not the handler has been added.

**Comment by falkartis** [comment]
Refactoring the code isn't currently an option, so I'll try out the HashSet strategy, Thank you.

**Comment by falkartis** [comment]
OK finally Refactoring has turned into an option.

Although it's kind of wired that the triggers have to be added to static properties.

I couldn't get the  [Usage with dependency injection](https://github.com/NickStrupat/EntityFramework.Triggers#usage-with-dependency-injection) example to work. I found the `IApplicationBuilder.UseTriggers` extension method in this repository, but didn't find it in the NuGet.

**Comment by NickStrupat** [comment]
The dependency injection extensions for adding the triggers via DI are in another NuGet package...

https://www.nuget.org/packages/NickStrupat.EntityFramework.Triggers.AspNetCore/
https://www.nuget.org/packages/NickStrupat.EntityFrameworkCore.Triggers.AspNetCore/

**Comment by falkartis** [comment]
Ok, my fault I was searching in the base Nuget.
Thanks.
