### ISSUE TITLE
Will Changes to the Database trigger events?

### ISSUE THREAD

**Issue by DevSelchow** [NickStrupat/EntityFramework.Triggers#58]
After reading the the Readme I am still unsure if the Triggers will work if an third-party program makes changes directly to the Database or are they only designed to work within one instance of EF.   
Could I use this to "send" events between to EF instances connected to the same database ?

**Comment by NickStrupat** [comment]
Sorry for the delayed response. This feature is not implemented currently. It would be very nice to have this implemented.

**Comment by DevSelchow** [comment]
Thank you for the answer
