### ISSUE TITLE
Trigger Updating: entry.Original exception

### ISSUE THREAD

**Issue by kongres** [NickStrupat/EntityFramework.Triggers#6]
Hello Nick.

Thank you for the great library. It is really very useful and flexible library.

I have issue with trigger on event "Updating"

My base entity:

```
    public class BaseEntity : ITriggerable
    {
        static BaseEntity()
        {
            Triggers<BaseEntity>.Inserting += entry => entry.Entity.DateCreated = entry.Entity.DateModified = DateTime.UtcNow;
            Triggers<BaseEntity>.Updating += entry => entry.Entity.DateModified = DateTime.UtcNow;
        }

        public BaseEntity()
        {
            Id = Guid.NewGuid().ToString("N");
        }

        public void SetId(string id)
        {
            Id = id;
        }

        [Key]
        public string Id { get; private set; }

        public DateTime DateCreated { get; set; }

        public DateTime DateModified { get; set; }

    }
```

My main model:

```
public class RequestInfo : BaseEntity
    {
        static RequestInfo()
        {
            // change status when reviewer was assigned
            Triggers<RequestInfo>.Updating += entry =>
            {
                if (!string.IsNullOrEmpty(entry.Original.AssignedToId) && !string.IsNullOrEmpty(entry.Entity.AssignedToId) && entry.Entity.Status == RequestStatus.New)
                    entry.Entity.Status = RequestStatus.InProgress;
            };
        }


        public RequestStatus Status { get; set; }

        public string AssignedToId { get; set; }
   }
```

But when event of trigger is hired I see error
![image](https://cloud.githubusercontent.com/assets/7360716/16405100/a3d64f22-3d0d-11e6-855e-9afe0e913af5.png)

My dbContext is inherited from DbContextWithTriggers and I have several events on Updating for this model

Maybe I did something wrong. Please let me know my mistake or suggestion to fix it.

**Comment by NickStrupat** [comment]
Thanks for the positive feedback! I'm glad to know that people are finding my library useful.

The image you posted is the debugger hover-over view of the entry object. I'm guessing the debugger caught an exception there and you took a screenshot of the entry object at the line the exception was thrown. Is that correct?

Either way, I tried the following program to try to reproduce your error. I didn't get any errors and the program ran as I expected. All I did was run in the package manager console `install-package entityframework.triggers`.

```
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using EntityFramework.Triggers;

namespace EntityFramework.Triggers_Issue_6_Testing {
    class Program {
        static void Main(string[] args) {
            using (var context = new Context())
            {
                var ri = new RequestInfo();
                context.RequestInfos.Add(ri);
                context.SaveChanges();
                ri.Text = "test"; // trigger the update
                context.SaveChanges();
            }
        }
    }

    public class Context : DbContextWithTriggers {
        public virtual DbSet<RequestInfo> RequestInfos { get; set; }
    }

    public class BaseEntity : ITriggerable {
        static BaseEntity() {
            Triggers<BaseEntity>.Inserting += entry => entry.Entity.DateCreated = entry.Entity.DateModified = DateTime.UtcNow;
            Triggers<BaseEntity>.Updating += entry => entry.Entity.DateModified = DateTime.UtcNow;
        }

        public BaseEntity() {
            Id = Guid.NewGuid().ToString("N");
        }

        public void SetId(string id) {
            Id = id;
        }

        [Key]
        public string Id { get; private set; }

        public DateTime DateCreated { get; set; }

        public DateTime DateModified { get; set; }

    }

    public class RequestInfo : BaseEntity {
        static RequestInfo() {
            // change status when reviewer was assigned
            Triggers<RequestInfo>.Updating += entry => {
                if (!string.IsNullOrEmpty(entry.Original.AssignedToId) && !string.IsNullOrEmpty(entry.Entity.AssignedToId) && entry.Entity.Status == RequestStatus.New)
                    entry.Entity.Status = RequestStatus.InProgress;
            };
        }

        public string Text { get; set; } // Added by NickStrupat

        public RequestStatus Status { get; set; }

        public string AssignedToId { get; set; }
    }

    public enum RequestStatus {
        InProgress,
        New
    }
}
```

**Comment by NickStrupat** [comment]
Does the error occur when you just have the one update trigger, or only when you have multiple?

**Comment by kongres** [comment]
Thank for the fastest response.

Yes. I used debbuger to catch this exception. It occurs with one trigger and with multiple triggers. So I think it doesn't matter in this case.

Your sample gave me idea what is reason. I use async methods for working with DB. My project is MVC + Web API 2 based on Repository + UnitOfWork pattern. All my methods work with async/await.

I will try to create a test project to reproduce this issue and will send you (maybe I will find reason while will create a test project).

**Comment by NickStrupat** [comment]
I wonder if the async behaviour is breaking the functionality...

I'm currently refactoring my `EntityFramework.TypedOriginalValues` to support EntitityFrameworkCore and .NET Core, so i'll put some good unit tests in there to make it more robust. It'll be a few days before I can get that fix over to this library.

That said, I'll put out a hotfix if it's something simple :)

**Comment by kongres** [comment]
Hello Nick. 

I've investigated my project and found reason. My entity has private empty constructor. It was reason of exception. I think you need to support this behaviour because sometimes we need to have DB entity with private default constructors (EF supports it).

But I have two more issue. I changed my private construdtor to public and now I can get access to Original property but:
1) Original entity looks like updated entity, so it has new values
2) I can get access to related entities with this entity

![image](https://cloud.githubusercontent.com/assets/7360716/16515608/9ee3bc64-3f7b-11e6-996b-f8c877d26c86.png)

On sceenshot I show my Original property which must have AssignedToId = null
Entity AssignedTo has public constructor and also is inherited from BaseEntity.

**Comment by kongres** [comment]
About first issue. I've found reason.

For updating model I used the following code:

```
        public virtual T Update(T entity)
        {
            Dbset.Attach(entity);
            dataContext.Entry(entity).State = EntityState.Modified;
            return entity;
        }
```

I changed it to:

```
        public virtual T Update(T entity)
        {
            Dbset.AddOrUpdate(entity);
            return entity;
        }
```

And it starts to work.

But I still have problem with second issue. Related entities are loaded for entry.Entity but are not loaded for entry.Original.

**Comment by NickStrupat** [comment]
The code which builds the original entity object is only getting the default constructor, so that explains your original error. That's a quick fix.

For your new first issue, I'll have to refresh my knowledge on how your first update code will effect the behaviour.

For your new second issue, that is unfortunately a limitation of the change tracking API in Entity Framework. It only offers `OriginalValue` for simple properties

I'll be writing unit tests for the project for the next couple of days. I'll see if I can figure out how to get a snapshot of original related entities to work.

**Comment by LightRay2** [comment]
Thanks for very useful package!

A also have a problem. Entry.Original also throws an exception in my case in Updated eventHandler. System.TypeInitializationException. I'll provide more info later.

**Comment by LightRay2** [comment]
![image](https://cloud.githubusercontent.com/assets/6893563/18224107/c616bb94-71d3-11e6-86db-b8abeb0f979d.png)

**Comment by LightRay2** [comment]
And another sample
![image](https://cloud.githubusercontent.com/assets/6893563/18224128/77bb1b92-71d4-11e6-8e13-6058e1d3d343.png)
where the comments class is simplest
![image](https://cloud.githubusercontent.com/assets/6893563/18224132/9dca8c8c-71d4-11e6-82d3-b188d404abf6.png)

**Comment by LightRay2** [comment]
Probably, in most cases developer doesn't really need original entity. It's enough to get access to list of changed property names as strings.
For my needs I implemented this in the following way.
![image](https://cloud.githubusercontent.com/assets/6893563/18224431/63a13aca-71dd-11e6-92d8-b7f1c4b4b797.png)

**Comment by NickStrupat** [comment]
@LightRay2 The problem you've encountered is that the original values object of `authors` is calling the `authors` constructor, which is trying to set the `Pictures` property (not allowed on a proxy object). As far as I know, there is no way to skip calling the base class constructor, but i'll see if I can figure it out.

**Comment by NickStrupat** [comment]
@LightRay2 I've figured out how to avoid calling the base entity constructor. I've updated the EntityFramework.TypedOriginalValues package.
