### ISSUE TITLE
Bug: cancelling event causes all other entities events to be cancelled too 

### ISSUE THREAD

**Issue by be4i** [NickStrupat/EntityFramework.Triggers#61]
Hello,

I have a soft delete trigger, and this causes stackoverflow when trying to add/remove same entities at once with async.With same debugging i noticed this [line](https://github.com/NickStrupat/EntityFramework.Triggers/blob/6353e6422fab04a0cd1d5ea586435b8c73a6f1f0/src/EntityFrameworkCore.Triggers/TriggerInvokerAsync.cs#L26), witch causes all other entity events after that to be cancelled.You can also see that in the sync version [here](https://github.com/NickStrupat/EntityFramework.Triggers/blob/6353e6422fab04a0cd1d5ea586435b8c73a6f1f0/src/EntityFrameworkCore.Triggers/TriggerInvoker.cs#L25) the variable is inside the loop as it should be.When i moved the canceled variable inside the loop my problem with stackoverflow was fixed.

**Comment by NickStrupat** [comment]
Thank you for the note. This is a bug. I'll look into fixing this.

**Comment by NickStrupat** [comment]
@be4i This should now be fixed on the latest NuGet package. Feel free to re-open this if it doesn't work :)
