### ISSUE TITLE
Multiple Updated Events Fired

### ISSUE THREAD

**Issue by mglodack** [NickStrupat/EntityFramework.Triggers#9]
Hello,

I'm currently hitting an issue where I save an entity with my `DbContext` and that triggers **multiple** `Updated` events.

If I have something like...

``` cs
public MyEntity()
{
   Triggers<MyEntity>.Updated += _Updated;
}

void _Updated(IAfterChangeEntry<MyEntity> entry)
{
   var eventEntity = _GetEventEntity(entry.Entity); // Assume this already exists
   entry.Context.Set<Event>().Add(eventEntity);

   // Do I call SaveChanges here?
   entry.Context.SaveChanges();
}
```

Where exactly do I call SaveChanges?

**Comment by NickStrupat** [comment]
Hi,

Unless you've made a typo in your posted code, the event handler should only be added once using the static events, which is easiest by using the static constructor...

``` csharp
static MyEntity()  // static constructor which runs once
{
    Triggers<MyEntity>.Updated += _Updated; // attach a handler once
}
```

The other option is to add an event handler to each individual object. This has a potential performance issue, yet is useful if your entities need different event handlers for different situations but inheritance isn't an option...

``` csharp
public MyEntity() // default constructor which runs every time a MyEntity is created
{
    this.Triggers().Updated += x => {}; // attach a handler to each MyEntity when it is created.
}
```

Make sure that if you're using the static events, you're only adding to them in static constructors or some other one-time initialization object.

As for calling `SaveChanges` within an event handler, that should work fine as long as you're careful not create a loop of inter-dependent events. For example, there's nothing in the library right now stopping preventing code from doing this kind of thing...

``` csharp
class B
{
    static A()
    {
        Triggers<A, MyContext>.Inserted += x => {
            x.Context.Bs.Add(new B());
            x.Context.SaveChanges(); // this will trigger the event defined below
        };
    }
}
class B
{
    static B()
    {
        Triggers<B, MyContext>.Inserted += x => {
            x.Context.As.Add(new A());
            x.Context.SaveChanges(); // this will trigger the event defined above
        };
    }
}
```

You also want to be careful to not call `SaveChanges` many times.

**Comment by NickStrupat** [comment]
I'm wondering if it makes sense for the library to call `SaveChanges` again after all the "after" events have been raised. It might be an easily achievable "pit of success".

**Comment by NickStrupat** [comment]
Just thought of something else: would your required logic work if you use the `Updating` event instead. changes made in that event are saved by the single call to `DbContext.SaveChanges` made inside `DbContextWithTriggers.SaveChanges`

**Comment by mglodack** [comment]
That could potentially work.

I'm assuming EF would rollback all of those changes within a transaction if something failed.

As a consumer of this library are we supposed to call `SaveChanges` within the event handler for events that are fired after an entity has been created/updated/deleted in the database?

**Comment by NickStrupat** [comment]
@mglodack, where did you end up with this issue?

You can call `SaveChanges` within the event handler for "after" triggers, just be careful not to create a loop.
